github: [bubblesthedev, fnbubbles420org] # GitHub Sponsors-enabled usernames
custom: ['https://fnbubbles420.org','https://fnbubbles420.org/volunteer','https://fnbubbles420.org/discordinvite','https://fnbubbles420.org/donate'] # Donation link , Volunteer link / Discord link
